CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset emotion-twitter --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset emotion-twitter --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset emotion-twitter --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset emotion-twitter --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset emotion-twitter --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset pos-idn --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset pos-idn --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset pos-idn --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset pos-idn --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset pos-idn --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset ner-grit --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset ner-grit --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset ner-grit --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset ner-grit --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset ner-grit --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset absa-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset absa-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset absa-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset absa-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset absa-airy --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset term-extraction-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset term-extraction-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset term-extraction-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset term-extraction-airy --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset term-extraction-airy --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset entailment-ui --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset entailment-ui --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset entailment-ui --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset entailment-ui --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset entailment-ui --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset doc-sentiment-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset doc-sentiment-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset doc-sentiment-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset doc-sentiment-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset doc-sentiment-prosa --no_special_token

CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint scratch --step_size 1 --gamma 0.5 --experiment_name scratch_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset keyword-extraction-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint word2vec --step_size 1 --gamma 0.5 --experiment_name word2vec_b16_step1_gamma0.5_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset keyword-extraction-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-twitter --step_size 1 --gamma 0.8 --experiment_name fasttext_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset keyword-extraction-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset keyword-extraction-prosa --no_special_token
CUDA_VISIBLE_DEVICES=$1 python3 main.py --n_epochs 100 --train_batch_size 16 --model_checkpoint fasttext-cc-id-no-oov --step_size 1 --gamma 0.8 --experiment_name fasttext-cc-id-no-oov_b16_step1_gamma0.8_lr6.25e-5_early10_nst --lr 6.25e-5 --early_stop 10 --dataset keyword-extraction-prosa --no_special_token